apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rag-app-dev

resources:
  - namespace.yaml
  - ../../base
  - ingress.yaml
  - backend-external-secret.yaml
  - ingestion-external-secret.yaml

patches:
  - target:
      kind: Deployment
      name: backend
    patch: |
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: ConfigMap
      name: backend-config
    patch: |
      - op: replace
        path: /data/ENVIRONMENT
        value: "development"
      - op: replace
        path: /data/DEBUG
        value: "true"
      - op: replace
        path: /data/POSTGRES_HOST
        value: "ragapp-dev-psql.ragapp-dev.postgres.database.azure.com"
      - op: replace
        path: /data/RABBITMQ_HOST
        value: "rabbitmq.rag-platform-dev.svc.cluster.local"
      - op: replace
        path: /data/S3_ENDPOINT_URL
        value: "http://10.30.17.10:9000"
      - op: replace
        path: /data/S3_REGION
        value: "ap-southeast-5"
  - target:
      kind: ConfigMap
      name: ingestion-config
    patch: |
      - op: replace
        path: /data/ENVIRONMENT
        value: "development"
      - op: replace
        path: /data/POSTGRES_HOST
        value: "ragapp-dev-psql.ragapp-dev.postgres.database.azure.com"
      - op: replace
        path: /data/RABBITMQ_HOST
        value: "rabbitmq.rag-platform-dev.svc.cluster.local"
      - op: replace
        path: /data/S3_ENDPOINT_URL
        value: "http://10.30.17.10:9000"
      - op: replace
        path: /data/S3_REGION
        value: "ap-southeast-5"

images:
  - name: rag-app/backend
    newName: replace-me.azurecr.io/rag-app/backend
    newTag: dev
  - name: rag-app/ingestion
    newName: replace-me.azurecr.io/rag-app/ingestion
    newTag: dev
