"""initial commit

Revision ID: c6af759ba9e2
Revises: 
Create Date: 2026-05-04 23:00:35.269214
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
from pgvector.sqlalchemy import VECTOR


# revision identifiers, used by Alembic.
revision: str = 'c6af759ba9e2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('document_extractions',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_name', sa.Text(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('tables', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('embedding', VECTOR(1536), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_doc_extractions_embedding', 'document_extractions', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('idx_doc_extractions_metadata', 'document_extractions', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index('idx_doc_extractions_name', 'document_extractions', ['document_name'], unique=False)
    op.create_table('session',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thread',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thread')
    op.drop_table('session')
    op.drop_index('idx_doc_extractions_name', table_name='document_extractions')
    op.drop_index('idx_doc_extractions_metadata', table_name='document_extractions', postgresql_using='gin')
    op.drop_index('idx_doc_extractions_embedding', table_name='document_extractions', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('document_extractions')
    # ### end Alembic commands ###
