apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ingestion-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: ingestion-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: ragapp-prod-postgres-user
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: ragapp-prod-postgres-password
    - secretKey: RABBITMQ_USER
      remoteRef:
        key: ragapp-prod-rabbitmq-user
    - secretKey: RABBITMQ_PASS
      remoteRef:
        key: ragapp-prod-rabbitmq-password
    - secretKey: S3_ACCESS_KEY
      remoteRef:
        key: ragapp-prod-s3-access-key
    - secretKey: S3_SECRET_KEY
      remoteRef:
        key: ragapp-prod-s3-secret-key
    - secretKey: OPENAI_API_KEY
      remoteRef:
        key: ragapp-prod-openai-api-key
    - secretKey: OPENAI_BASE_URL
      remoteRef:
        key: ragapp-prod-openai-base-url
