apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rag-app-prod

resources:
  - namespace.yaml
  - ../../base
  - ingress.yaml
  - backend-external-secret.yaml
  - ingestion-external-secret.yaml

patches:
  - target:
      kind: Deployment
      name: backend
    patch: |
      - op: replace
        path: /spec/replicas
        value: 3
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 500m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 1Gi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: "2"
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 2Gi
  - target:
      kind: Deployment
      name: ingestion-worker
    patch: |
      - op: replace
        path: /spec/replicas
        value: 2
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: "1"
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 2Gi
  - target:
      kind: ConfigMap
      name: backend-config
    patch: |
      - op: replace
        path: /data/ENVIRONMENT
        value: "production"
      - op: replace
        path: /data/DEBUG
        value: "false"
      - op: replace
        path: /data/POSTGRES_HOST
        value: "ragapp-prod-psql.ragapp-prod.postgres.database.azure.com"
      - op: replace
        path: /data/RABBITMQ_HOST
        value: "rabbitmq.rag-platform-prod.svc.cluster.local"
      - op: replace
        path: /data/S3_ENDPOINT_URL
        value: "http://10.40.17.10:9000"
      - op: replace
        path: /data/S3_REGION
        value: "ap-southeast-5"
  - target:
      kind: ConfigMap
      name: ingestion-config
    patch: |
      - op: replace
        path: /data/ENVIRONMENT
        value: "production"
      - op: replace
        path: /data/POSTGRES_HOST
        value: "ragapp-prod-psql.ragapp-prod.postgres.database.azure.com"
      - op: replace
        path: /data/RABBITMQ_HOST
        value: "rabbitmq.rag-platform-prod.svc.cluster.local"
      - op: replace
        path: /data/S3_ENDPOINT_URL
        value: "http://10.40.17.10:9000"
      - op: replace
        path: /data/S3_REGION
        value: "ap-southeast-5"

images:
  - name: rag-app/backend
    newName: replace-me.azurecr.io/rag-app/backend
    newTag: stable
  - name: rag-app/ingestion
    newName: replace-me.azurecr.io/rag-app/ingestion
    newTag: stable
