apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rabbitmq-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: rabbitmq-secrets
    creationPolicy: Owner
  data:
    - secretKey: RABBITMQ_DEFAULT_USER
      remoteRef:
        key: ragapp-dev-rabbitmq-user
    - secretKey: RABBITMQ_DEFAULT_PASS
      remoteRef:
        key: ragapp-dev-rabbitmq-password
