apiVersion: v1
kind: Service
metadata:
  name: minio
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: rag-app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: minio
  ports:
    - port: 9000
      targetPort: 9000
      name: api
      protocol: TCP
    - port: 9001
      targetPort: 9001
      name: console
      protocol: TCP
