apiVersion: v1
kind: Secret
metadata:
  name: ingestion-secrets
type: Opaque
stringData:
  POSTGRES_USER: rag_app
  POSTGRES_PASSWORD: rag_app_pass
  RABBITMQ_USER: guest
  RABBITMQ_PASS: guest
  S3_ACCESS_KEY: minioadmin
  S3_SECRET_KEY: minioadmin
  OPENAI_API_KEY: ""
  OPENAI_BASE_URL: https://api.openai.com/v1
